title: RPG Codebase
description: Каталог ссылок на ролевые проекты

theme: jekyll-theme-primer

collections:
  larp:
    output: true
    permalink: /larp/:name
  trpg:
    output: true
    permalink: /trpg/:name


exclude:
  - .gitignore
  - .idea
  - __howto